### ISSUE TITLE
panic on getProfileConfig

### ISSUE THREAD

**Issue by tekumara** [glassechidna/awsweb#21]
```
$ awsweb env myaccount
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1 pc=0x834ea7]

goroutine 1 [running]:
github.com/go-ini/ini.(*File).GetSection(0x0, 0xc0000b7101, 0x7, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/go-ini/ini@v1.37.0/file.go:113 +0x67
github.com/glassechidna/awscredcache.(*AwsCacheCredProvider).getProfileConfig(0xc0001cd200, 0xc0000b7101, 0x7, 0xc0000b7101, 0x7, 0x0)
        /home/runner/go/pkg/mod/github.com/glassechidna/awscredcache@v0.0.0-20191108071202-3748056f08c8/creds.go:143 +0x19c
github.com/glassechidna/awscredcache.(*AwsCacheCredProvider).getProfileConfig(0xc0001cd200, 0x7fff69bf0623, 0x3, 0xfaa7e0, 0x7f1248e6e7d0, 0x0)
        /home/runner/go/pkg/mod/github.com/glassechidna/awscredcache@v0.0.0-20191108071202-3748056f08c8/creds.go:117 +0x80b
github.com/glassechidna/awscredcache.(*AwsCacheCredProvider).Retrieve(0xc0001cd200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x847459, ...)
        /home/runner/go/pkg/mod/github.com/glassechidna/awscredcache@v0.0.0-20191108071202-3748056f08c8/creds.go:47 +0x58
github.com/glassechidna/awsweb/cmd.doEnv(0xc06720, 0xc0001cd200, 0x7fff69bf0623, 0x3, 0x0, 0x0, 0xc0000ad300)
        /home/runner/work/awsweb/awsweb/cmd/env.go:57 +0x49
github.com/glassechidna/awsweb/cmd.init.1.func1(0xc0001cb400, 0xc000097ac0, 0x1, 0x1)
        /home/runner/work/awsweb/awsweb/cmd/env.go:45 +0x10e
github.com/spf13/cobra.(*Command).execute(0xc0001cb400, 0xc000097a70, 0x1, 0x1, 0xc0001cb400, 0xc000097a70)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xfa0840, 0x441f0a, 0xf63100, 0xc000048778)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/glassechidna/awsweb/cmd.Execute()
        /home/runner/work/awsweb/awsweb/cmd/root.go:40 +0x31
main.main()
        /home/runner/work/awsweb/awsweb/main.go:20 +0x20
```

**Comment by tekumara** [comment]
Looks like I'm missing _~/.aws/credentials_.

I ran `aws configure` and supplied a AWS Access Key ID and AWS Secret Access Key which created the credentials file.
