### ISSUE TITLE
panic at awscredcache.mfaAuthenticatedCredentials.func1.1

### ISSUE THREAD

**Issue by tekumara** [glassechidna/awsweb#22]
```
$ awsweb myaccount

Assume Role MFA token code: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x849f6f]

goroutine 1 [running]:
github.com/glassechidna/awscredcache.mfaAuthenticatedCredentials.func1.1(0xc0001fc000)
        /home/runner/go/pkg/mod/github.com/glassechidna/awscredcache@v0.0.0-20191108071202-3748056f08c8/creds.go:265 +0x4f
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc0001fc2f0, 0xc0001fc000)
        /home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.25.30/aws/request/handlers.go:261 +0x98
github.com/aws/aws-sdk-go/aws/request.(*Request).Send.func1(0xc0001fc000)
        /home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.25.30/aws/request/request.go:491 +0x39
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc0001fc000, 0xbfdc40, 0xc0001c56b0)
        /home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.25.30/aws/request/request.go:504 +0x2b3
github.com/aws/aws-sdk-go/service/sts.(*STS).GetSessionTokenWithContext(0xc0000aa198, 0xc087e0, 0xc0000a6010, 0xc00009d560, 0xc0000aa1a0, 0x1, 0x1, 0x14, 0xc109c0, 0xc0000aa198)
        /home/runner/go/pkg/mod/github.com/aws/aws-sdk-go@v1.25.30/service/sts/api.go:1160 +0xae
github.com/glassechidna/awscredcache.mfaAuthenticatedCredentials(0xc0000a95c1, 0x14, 0xc0000a2631, 0x28, 0x0, 0x0, 0xa5636c, 0x14, 0xc000102441, 0x35, ...)
        /home/runner/go/pkg/mod/github.com/glassechidna/awscredcache@v0.0.0-20191108071202-3748056f08c8/creds.go:263 +0x473
github.com/glassechidna/awscredcache.(*AwsCacheCredProvider).getProfileConfig(0xc0001c52f0, 0xc0000a70f1, 0x7, 0xc0000a70f1, 0x7, 0x0)
        /home/runner/go/pkg/mod/github.com/glassechidna/awscredcache@v0.0.0-20191108071202-3748056f08c8/creds.go:170 +0x686
github.com/glassechidna/awscredcache.(*AwsCacheCredProvider).getProfileConfig(0xc0001c52f0, 0x7fffff5ee53f, 0x7, 0xfaa7e0, 0x7fdada66e7d0, 0x0)
        /home/runner/go/pkg/mod/github.com/glassechidna/awscredcache@v0.0.0-20191108071202-3748056f08c8/creds.go:117 +0x80b
github.com/glassechidna/awscredcache.(*AwsCacheCredProvider).Retrieve(0xc0001c52f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x847459, ...)
        /home/runner/go/pkg/mod/github.com/glassechidna/awscredcache@v0.0.0-20191108071202-3748056f08c8/creds.go:47 +0x58
github.com/glassechidna/awsweb/cmd.doEnv(0xc06720, 0xc0001c52f0, 0x7fffff5ee53f, 0x7, 0xc000024046, 0xc, 0xc00009d300)
        /home/runner/work/awsweb/awsweb/cmd/env.go:57 +0x49
github.com/glassechidna/awsweb/cmd.init.1.func1(0xc0001e3180, 0xc000085ac0, 0x1, 0x1)
        /home/runner/work/awsweb/awsweb/cmd/env.go:45 +0x10e
github.com/spf13/cobra.(*Command).execute(0xc0001e3180, 0xc000085a70, 0x1, 0x1, 0xc0001e3180, 0xc000085a70)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xfa0840, 0x441f0a, 0xf63100, 0xc000040778)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/glassechidna/awsweb/cmd.Execute()
        /home/runner/work/awsweb/awsweb/cmd/root.go:40 +0x31
main.main()
        /home/runner/work/awsweb/awsweb/main.go:20 +0x20
```

**Comment by tekumara** [comment]
The above was on a new machine. Reran awsweb as per above and the issue went away.
